### ISSUE TITLE
Make a checklist for doing a release

### ISSUE THREAD

**Issue by kdmurray91** [kdmurray91/kWIP#18]
-  [ ] static build
  - [ ] has documentation?
  - [ ] works on CentOS 6 and Debian Squeeze?
  - [ ] version is correct
- [ ] copy-paste of install instructions works?
   - [ ] Clean ubuntu LTS
   - [ ] Debian sid & stable
   - [ ]  centos 6
- [ ] github release notes
